
int bitAnd(int, int);
int test_bitAnd(int, int);
int copyLSB(int);
int test_copyLSB(int);
int leastBitPos(int);
int test_leastBitPos(int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int bitCount(int);
int test_bitCount(int);
int tmax();
int test_tmax();
int divpwr2(int, int);
int test_divpwr2(int, int);
int isNonNegative(int);
int test_isNonNegative(int);
int isGreater(int, int);
int test_isGreater(int, int);
int absVal(int);
int test_absVal(int);
int isPower2(int);
int test_isPower2(int);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
